name: 'Test Report'
on:
  workflow_run:
    workflows: ['Pull request tests']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Mocha Tests                  # Name of the check run which will be created
        path: 'server/servertest.json'                     # Path to test results (inside artifact .zip)
        reporter: mocha-json              # Format of test results